### ISSUE TITLE
[PE-D][Tester D] Graphical User Interface in UG is not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-1/tp#166]
In the UG, the image of the GUI provided does not match the actual application. This does not help the readers to orientate themselves to your app.
![image.png](https://raw.githubusercontent.com/samuelmui8/ped/main/files/ac4013ab-5598-419f-8ad4-2548ef745834.png)

![image.png](https://raw.githubusercontent.com/samuelmui8/ped/main/files/0a9cd8fc-80a8-4f57-8e62-9b285a39fb1f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: samuelmui8/ped#1

**Comment by raydenlim** [comment]
Hmm... we are not sure how u got the OLD UG haha, did u prep the PE-D before 10 am xD

Invalid concern ~~
