### ISSUE TITLE
[PE-D][Tester E] Confusion regarding assignment allocation to students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-1/tp#183]
For this section, I am just abit confused regarding the assignments allocated to students. In the UG, there is a command for "viewassignments" but I cant seem to find the one for adding or removing assignments. I tried ctrl find also but not sure if I missed it out in the UG. If there is no feature to add or remove assignments that I am not sure how to utilise the "viewassignments" command as well.

![image.png](https://raw.githubusercontent.com/zannloo/ped/main/files/3560e83a-6fd9-4205-9f56-058ec97f949a.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: zannloo/ped#5

**Comment by wesho1107** [comment]
With the current implementation, there are no `add` or `remove` feature for Assignments with the justification that students have fixed amount of Assignments in a semester.

`viewassignments INDEX` is to view the students list of assignments with provided comments and grades.

**Comment by Originalidk** [comment]
As CS1101S sets the assignments for students, there is no good reason to make Avengers have to add and remove the assignments. Setting the assignments in the application makes it easier for Avengers to keep track of Source Academy assignments without having to add them in manually. Perhaps we could add it in as a future implementation for customisation.

**Comment by raydenlim** [comment]
~~Invalid concern
