### ISSUE TITLE
[PE-D][Tester C] Typo error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-1/tp#187]
![tab error.png](https://raw.githubusercontent.com/Jonyxzx/ped/main/files/6f1d76a4-0155-4728-ac91-435d5c704a04.png)

Missing bracket

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Jonyxzx/ped#3

**Comment by wesho1107** [comment]
Resolved by adding the missing ')' to error statement.
