### ISSUE TITLE
[PE-D][Tester C] Broken feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-1/tp#196]
![Absent error.png](https://raw.githubusercontent.com/Jonyxzx/ped/main/files/12ec8fe5-48ff-4e68-96b3-44f932fdb611.png)

Alex is not removed after running the command shown

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Jonyxzx/ped#9

**Comment by ldinghan** [comment]
Unable to replicate
