### ISSUE TITLE
Any `edit` comand replaces the old student object, causing commands downstream to not work as intended

### ISSUE THREAD

**Issue by raydenlim** [AY2324S1-CS2103T-T15-1/tp#225]
Steps to replicate bug:

`editgradedtest INDEX PREFIX/SCORE`
** or any edit functions in general**

Subsequently, any command that references to the old `student object` such as `takeattendance` would not work as intended

**Comment by wesho1107** [comment]
Resolved together with bugs from consultation and session, refer to `ModelManager.setPerson()`.
