### ISSUE TITLE
DG: Sequence Diagram Help Needed

### ISSUE THREAD

**Issue by Respirayson** [AY2324S1-CS2103T-T15-1/tp#275]
![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/a4855b37-8fb2-4a59-8231-f190a579a54b)

Guys, should the activation bar here be broken up into 2?

**Comment by raydenlim** [comment]
I think best to split it.

**Comment by wesho1107** [comment]
Resolved for DeleteTask and UpdateTaskProgress
