### ISSUE TITLE
DG: Sequence Diagram help

### ISSUE THREAD

**Issue by raydenlim** [AY2324S1-CS2103T-T15-1/tp#276]
![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/109991591/77295f48-3e2a-4445-bd5c-803e405fe098)

Not sure if this is a typo, some uses Person, some uses Student

**Comment by Respirayson** [comment]
I should've followed the method names that we have but maybe I saw wrongly

**Comment by wesho1107** [comment]
It is not a typo, it is following the method names.
