### ISSUE TITLE
UG: parallel language

### ISSUE THREAD

**Issue by Respirayson** [AY2324S1-CS2103T-T15-1/tp#280]
No parallel language in the convention section

![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/0fed46f5-a057-4b1c-a851-ae9241f3fdb9)

![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/a777d22b-9ff5-4d86-bda5-d3d554fd9142)

**Comment by raydenlim** [comment]
Might want to standardise this too:
![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/109991591/4cc5c486-d76c-4971-a67f-defc230658cd)
