### ISSUE TITLE
UG: Quick Start

### ISSUE THREAD

**Issue by Respirayson** [AY2324S1-CS2103T-T15-1/tp#282]
- [x] coming soon needs to be deleted
![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/1ce29632-1acc-44c6-ae70-f7c429cd5317)

- [x] change to below for the details of each command
![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/8dc79af8-6a80-4e7c-913d-088bae753131)

**Comment by raydenlim** [comment]
I think the 2nd one is fine ah.
