### ISSUE TITLE
UG: Session Number of a tutorial

### ISSUE THREAD

**Issue by Respirayson** [AY2324S1-CS2103T-T15-1/tp#285]
index number of a session? cause I think its weird to bring up tutorial out of nowhere

![image](https://github.com/AY2324S1-CS2103T-T15-1/tp/assets/88478542/aeb9e836-eb69-4e52-8b17-7ca53eb75635)

**Comment by ldinghan** [comment]
I was thinking Session Number of a Session or something (as per my PR) since it really isn't an index either
