### ISSUE TITLE
Incorrect Create Consult Not Showing appropriate error message

### ISSUE THREAD

**Issue by Respirayson** [AY2324S1-CS2103T-T15-1/tp#68]
When running the create consult command with a person who is not in the task list:
- PersonNotFoundException is thrown in the console
- However, there is no error message shown on the command box

Minor issue but it would improve the UI and ease of use of the app

**Comment by ldinghan** [comment]
Agree with you, Create Session faces the same issue as well

**Comment by wesho1107** [comment]
Resolved with proper exception thrown.
